server:
  port: 8088

spring:
  application:
    name: account

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  kafka:
    consumer:
      bootstrap-servers: kafka-broker:9092
      group-id: mc-account-group
      # Явно указываем StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Разрешаем доверять всем пакетам (поскольку парсинг будет ручной)
      properties:
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

auth:
  service:
    url: http://auth:8081

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    ru.skillbox.socialnetwork.account: INFO
    ru.skillbox.socialnetwork.account.service: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cache: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %highlight(%-5level) - %cyan(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n"

#springdoc:
#  server-url: http://185.129.146.54:8765/api/v1/account