services:
  frontend-crm:
    container_name: frontend-crm
    build:
      context: .
      dockerfile: frontend-crm/Dockerfile
    ports:
      - "8083:3000"
    networks:
      - frontend-net

  frontend-shop:
    container_name: frontend-shop
    build:
      context: .
      dockerfile: frontend-shop/Dockerfile
    ports:
      - "8084:3000"
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge