spring:
  application:
    name: shop
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/frontend_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create}
    show-sql: ${HIBERNATE_SHOW_SQL:true}
  thymeleaf:
    prefix: classpath:/templates/

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}

liquibase:
  enabled: ${LIQUIBASE_ENABLED:false}
  default-schema: ${LIQUIBASE_DEFAULT_DB_SCHEMA:frontend_schema}

feign:
  clients:
    account-service:
      name: ${FEIGN_CLIENTS_ACCOUNT_SERVICE_NAME:account}
      url: ${FEIGN_CLIENTS_ACCOUNT_SERVICE_URL:http://localhost:8088}
    auth-service:
      name: ${FEIGN_CLIENTS_AUTH_SERVICE_NAME:auth}
      url: ${FEIGN_CLIENTS_AUTH_SERVICE_URL:http://localhost:8081}